// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxcTdzNJokpegRpDhtFcP2K7oIWjLFL2E',
    appId: '1:264596713640:web:158a6e1fc5b7ded2b7d29d',
    messagingSenderId: '264596713640',
    projectId: 'polimatch-f387e',
    authDomain: 'polimatch-f387e.firebaseapp.com',
    storageBucket: 'polimatch-f387e.appspot.com',
    measurementId: 'G-PQ8C7B7LPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlrSSjPtjBXatiglMhKAYyAymZPp0puUw',
    appId: '1:264596713640:android:f3ffb8d6f431aa77b7d29d',
    messagingSenderId: '264596713640',
    projectId: 'polimatch-f387e',
    storageBucket: 'polimatch-f387e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk7mYz5gghp1kKhgiU7DtgF0WckKvsJTo',
    appId: '1:264596713640:ios:6e395c11b7882fc3b7d29d',
    messagingSenderId: '264596713640',
    projectId: 'polimatch-f387e',
    storageBucket: 'polimatch-f387e.appspot.com',
    iosClientId: '264596713640-nvv2ihernfknu6ddj1o3c52b45go893a.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk7mYz5gghp1kKhgiU7DtgF0WckKvsJTo',
    appId: '1:264596713640:ios:39046bbcfe4686b5b7d29d',
    messagingSenderId: '264596713640',
    projectId: 'polimatch-f387e',
    storageBucket: 'polimatch-f387e.appspot.com',
    iosClientId: '264596713640-hs2h094vs2due5bu14au2be6d3aonef6.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto.RunnerTests',
  );
}
